# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5036eea46598b69efd0895b55640d3039da2f3bf3cb056c6b6f2c5c866bd47b423d97f6476dc92d086cd5f46decffda04cd2b2f1fc07d3cdc5946e570e513819

test:
  secret_key_base: 514fd27b904e5031137a0e03810d98e13315f2b1853d2b6c8d7ddcba03759b408a0ad44b6b1fa1bad249c93a43b84d8913d74facf2d5b526a8ec241fff83e9c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
